// MediCare Plus — Central doctor dataset
// Shared by: doctors.html (directory), doctor-profile.html, appointment.html
// In a larger app this would come from the backend (GET /api/doctors) —
// kept as static data here since doctor profiles don't change often and
// this keeps the directory/search instant without a network round trip.

const DOCTORS = [
  {
    id: 'sarah',
    name: 'Dr. Sarah Ahmed',
    specialty: 'Cardiologist',
    photo: '../images/dr-sarah.png',
    rating: 4.9,
    reviews: 210,
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dr. Sarah Ahmed has over 12 years of experience in cardiovascular care, specializing in preventive cardiology and heart rhythm disorders.',
    qualifications: ['MBBS — King Edward Medical University', 'FCPS Cardiology', 'Fellowship in Interventional Cardiology, UK'],
    languages: ['English', 'Urdu'],
    availability: {
      Monday: ['09:00 AM', '10:00 AM', '11:00 AM', '02:00 PM', '03:00 PM'],
      Tuesday: ['09:00 AM', '10:00 AM', '01:00 PM', '02:00 PM'],
      Wednesday: ['09:00 AM', '11:00 AM', '02:00 PM', '03:00 PM', '04:00 PM'],
      Thursday: ['10:00 AM', '11:00 AM', '01:00 PM'],
      Friday: ['09:00 AM', '10:00 AM', '02:00 PM'],
    },
  },
  {
    id: 'ahmed',
    name: 'Dr. Ahmed Raza',
    specialty: 'Neurologist',
    photo: '../images/dr-ahmed.png',
    rating: 4.8,
    reviews: 164,
    bio: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dr. Ahmed Raza focuses on headache disorders, epilepsy, and post-stroke rehabilitation planning.',
    qualifications: ['MBBS — Aga Khan University', 'FCPS Neurology', 'Diploma in Clinical Neurophysiology'],
    languages: ['English', 'Urdu'],
    availability: {
      Monday: ['10:00 AM', '11:00 AM', '01:00 PM'],
      Tuesday: ['09:00 AM', '10:00 AM', '03:00 PM', '04:00 PM'],
      Thursday: ['09:00 AM', '11:00 AM', '02:00 PM'],
      Friday: ['10:00 AM', '11:00 AM', '01:00 PM', '03:00 PM'],
    },
  },
  {
    id: 'fatima',
    name: 'Dr. Fatima Khan',
    specialty: 'Pediatrician',
    photo: '../images/dr-fatima.png',
    rating: 5.0,
    reviews: 302,
    bio: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris. Dr. Fatima Khan has dedicated her career to gentle, family-centered pediatric care from infancy through adolescence.',
    qualifications: ['MBBS — Dow Medical College', 'FCPS Pediatrics', 'Certified in Pediatric Emergency Care'],
    languages: ['English', 'Urdu', 'Punjabi'],
    availability: {
      Monday: ['09:00 AM', '10:00 AM', '11:00 AM', '02:00 PM'],
      Wednesday: ['09:00 AM', '10:00 AM', '01:00 PM', '02:00 PM', '03:00 PM'],
      Thursday: ['10:00 AM', '11:00 AM', '02:00 PM'],
      Saturday: ['10:00 AM', '11:00 AM', '12:00 PM'],
    },
  },
  {
    id: 'hassan',
    name: 'Dr. Hassan Ali',
    specialty: 'Orthopedic Surgeon',
    photo: '../images/dr-hassan.png',
    rating: 4.7,
    reviews: 128,
    bio: 'Duis aute irure dolor in reprehenderit in voluptate velit esse. Dr. Hassan Ali specializes in sports injuries, joint replacement, and minimally invasive orthopedic surgery.',
    qualifications: ['MBBS — University of Health Sciences', 'FCPS Orthopedic Surgery', 'Fellowship in Sports Medicine, Germany'],
    languages: ['English', 'Urdu'],
    availability: {
      Tuesday: ['09:00 AM', '10:00 AM', '11:00 AM'],
      Wednesday: ['01:00 PM', '02:00 PM', '03:00 PM'],
      Friday: ['09:00 AM', '10:00 AM', '11:00 AM', '02:00 PM'],
      Saturday: ['10:00 AM', '11:00 AM'],
    },
  },
  {
    id: 'ayesha',
    name: 'Dr. Ayesha Siddiqui',
    specialty: 'Dermatologist',
    photo: '../images/dr-ayesha.png',
    rating: 4.9,
    reviews: 176,
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dr. Ayesha Siddiqui treats a wide range of skin conditions and offers cosmetic dermatology consultations.',
    qualifications: ['MBBS — Fatima Jinnah Medical University', 'FCPS Dermatology', 'Certified in Aesthetic Medicine'],
    languages: ['English', 'Urdu'],
    availability: {
      Monday: ['01:00 PM', '02:00 PM', '03:00 PM'],
      Tuesday: ['09:00 AM', '10:00 AM', '11:00 AM'],
      Thursday: ['01:00 PM', '02:00 PM', '03:00 PM', '04:00 PM'],
    },
  },
  {
    id: 'bilal',
    name: 'Dr. Bilal Chaudhry',
    specialty: 'Dentist',
    photo: '../images/dr-bilal.png',
    rating: 4.8,
    reviews: 143,
    bio: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dr. Bilal Chaudhry provides preventive, restorative, and cosmetic dental care in a calm setting.',
    qualifications: ['BDS — de\'Montmorency College of Dentistry', 'RDS Licensed', 'Certified in Cosmetic Dentistry'],
    languages: ['English', 'Urdu'],
    availability: {
      Monday: ['09:00 AM', '10:00 AM', '02:00 PM'],
      Wednesday: ['09:00 AM', '10:00 AM', '11:00 AM'],
      Friday: ['01:00 PM', '02:00 PM', '03:00 PM'],
      Saturday: ['09:00 AM', '10:00 AM', '11:00 AM'],
    },
  },
  {
    id: 'sana',
    name: 'Dr. Sana Malik',
    specialty: 'General Physician',
    photo: '../images/dr-sana.png',
    rating: 4.9,
    reviews: 255,
    bio: 'Ut enim ad minim veniam, quis nostrud exercitation. Dr. Sana Malik is the first point of contact for most patients, handling everyday health concerns and referrals.',
    qualifications: ['MBBS — Allama Iqbal Medical College', 'MRCGP', 'Diploma in Family Medicine'],
    languages: ['English', 'Urdu'],
    availability: {
      Monday: ['09:00 AM', '10:00 AM', '11:00 AM', '01:00 PM', '02:00 PM'],
      Tuesday: ['09:00 AM', '10:00 AM', '11:00 AM'],
      Wednesday: ['09:00 AM', '10:00 AM', '01:00 PM'],
      Thursday: ['09:00 AM', '10:00 AM', '11:00 AM'],
      Friday: ['09:00 AM', '10:00 AM'],
    },
  },
  {
    id: 'omar',
    name: 'Dr. Omar Farooq',
    specialty: 'ENT Specialist',
    photo: '../images/dr-omar.png',
    rating: 4.6,
    reviews: 98,
    bio: 'Duis aute irure dolor in reprehenderit. Dr. Omar Farooq treats conditions of the ear, nose, and throat, from routine infections to more complex ENT surgery.',
    qualifications: ['MBBS — Nishtar Medical University', 'FCPS Otolaryngology', 'Fellowship in Head & Neck Surgery'],
    languages: ['English', 'Urdu'],
    availability: {
      Tuesday: ['10:00 AM', '11:00 AM', '02:00 PM'],
      Thursday: ['09:00 AM', '10:00 AM', '01:00 PM', '02:00 PM'],
      Saturday: ['11:00 AM', '12:00 PM'],
    },
  },
];

// Works both in the browser (script tag) and if ever required as a module
if (typeof module !== 'undefined') module.exports = DOCTORS;
