// NestFinder Pro — Central property dataset
// Shared by: index.html (featured), pages/listings.html (full grid + filters),
// and pages/property-detail.html (Day 2).

const PROPERTIES = [
  {
    id: 'villa-hillcrest',
    title: 'Hillcrest Luxury Villa',
    type: 'villa',
    purpose: 'sale',
    price: 285000,
    location: 'Gulberg, Lahore',
    bedrooms: 5,
    bathrooms: 5,
    area: 4200,
    image: '../images/prop-villa-1.png',
    homeImage: 'images/prop-villa-1.png',
    tag: 'Featured',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. A sun-filled villa with a private pool, landscaped garden, and panoramic hillside views — designed for effortless indoor-outdoor living.',
    amenities: ['Private Pool', 'Landscaped Garden', 'Smart Home System', '3-Car Garage', 'Home Theatre', 'Servant Quarters'],
    agentId: 'hamza',
  },
  {
    id: 'apt-skyline',
    title: 'Skyline Residences 12B',
    type: 'apartment',
    purpose: 'sale',
    price: 145000,
    location: 'DHA Phase 6, Karachi',
    bedrooms: 3,
    bathrooms: 3,
    area: 1850,
    image: '../images/prop-apartment-1.png',
    homeImage: 'images/prop-apartment-1.png',
    tag: 'New',
    description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. A high-floor residence with floor-to-ceiling windows, resort-style amenities, and unobstructed skyline views.',
    amenities: ['24/7 Concierge', 'Rooftop Pool', 'Fitness Center', 'Covered Parking', 'Backup Power', 'Kids Play Area'],
    agentId: 'sadia',
  },
  {
    id: 'office-metropolitan',
    title: 'The Metropolitan Tower — Floor 9',
    type: 'commercial',
    purpose: 'rent',
    price: 8500,
    location: 'Blue Area, Islamabad',
    bedrooms: 0,
    bathrooms: 4,
    area: 6200,
    image: '../images/prop-commercial-1.png',
    homeImage: 'images/prop-commercial-1.png',
    tag: 'For Rent',
    description: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris. A full-floor commercial unit in a Grade-A tower, fitted for a modern corporate headquarters.',
    amenities: ['Central AC', 'Conference Rooms', 'High-Speed Fiber', 'Reserved Parking', '24/7 Security', 'Elevator Priority Access'],
    agentId: 'usman',
  },
  {
    id: 'townhouse-elmwood',
    title: 'Elmwood Townhouse Row 4',
    type: 'townhouse',
    purpose: 'sale',
    price: 168000,
    location: 'Bahria Town, Lahore',
    bedrooms: 4,
    bathrooms: 4,
    area: 2600,
    image: '../images/prop-townhouse-1.png',
    homeImage: 'images/prop-townhouse-1.png',
    tag: 'Featured',
    description: 'Duis aute irure dolor in reprehenderit in voluptate velit esse. A family townhouse in a gated community, with private rooftop terrace and shared green courtyards.',
    amenities: ['Rooftop Terrace', 'Gated Community', 'Community Park', '2-Car Garage', 'Backup Generator', 'Store Room'],
    agentId: 'hamza',
  },
  {
    id: 'penthouse-crown',
    title: 'Crown Heights Penthouse',
    type: 'penthouse',
    purpose: 'sale',
    price: 495000,
    location: 'Clifton, Karachi',
    bedrooms: 4,
    bathrooms: 5,
    area: 5100,
    image: '../images/prop-penthouse-1.png',
    homeImage: 'images/prop-penthouse-1.png',
    tag: 'Exclusive',
    description: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia. A statement penthouse with a private terrace, sea-facing views, and bespoke interiors throughout.',
    amenities: ['Private Terrace', 'Sea View', 'Private Elevator', 'Wine Cellar', 'Home Automation', 'Staff Quarters'],
    agentId: 'sadia',
  },
  {
    id: 'studio-lofthouse',
    title: 'Lofthouse Studio 3C',
    type: 'studio',
    purpose: 'rent',
    price: 950,
    location: 'F-7, Islamabad',
    bedrooms: 1,
    bathrooms: 1,
    area: 620,
    image: '../images/prop-studio-1.png',
    homeImage: 'images/prop-studio-1.png',
    tag: 'For Rent',
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. A bright, efficient studio perfect for a single professional, moments from the capital's business district.",
    amenities: ['Furnished', 'High-Speed Internet', 'Rooftop Access', 'On-Site Laundry', 'Bike Storage'],
    agentId: 'usman',
  },
  {
    id: 'villa-marina',
    title: 'Marina Bay Villa',
    type: 'villa',
    purpose: 'rent',
    price: 4200,
    location: 'DHA Phase 8, Karachi',
    bedrooms: 4,
    bathrooms: 4,
    area: 3400,
    image: '../images/prop-villa-2.png',
    homeImage: 'images/prop-villa-2.png',
    tag: 'For Rent',
    description: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem. A relaxed coastal villa with a shaded courtyard, ideal for entertaining year-round.',
    amenities: ['Courtyard', 'Covered Parking', 'Maid Room', 'Central AC', 'Security Staff'],
    agentId: 'hamza',
  },
  {
    id: 'apt-orchid',
    title: 'Orchid Residency 5A',
    type: 'apartment',
    purpose: 'sale',
    price: 98000,
    location: 'Model Town, Lahore',
    bedrooms: 2,
    bathrooms: 2,
    area: 1240,
    image: '../images/prop-apartment-2.png',
    homeImage: 'images/prop-apartment-2.png',
    tag: 'New',
    description: 'At vero eos et accusamus et iusto odio dignissimos ducimus. A well-planned two-bedroom apartment close to parks, schools, and everyday conveniences.',
    amenities: ['Community Park', 'Covered Parking', 'Backup Power', 'Elevator', '24/7 Security'],
    agentId: 'sadia',
  },
  {
    id: 'office-galleria',
    title: 'Galleria Business Suite 4',
    type: 'commercial',
    purpose: 'sale',
    price: 210000,
    location: 'I-8 Markaz, Islamabad',
    bedrooms: 0,
    bathrooms: 3,
    area: 3100,
    image: '../images/prop-commercial-2.png',
    homeImage: 'images/prop-commercial-2.png',
    tag: 'Featured',
    description: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit. A ready-to-move commercial suite with excellent street visibility and footfall.',
    amenities: ['Street-Facing Storefront', 'Central AC', 'Loading Access', 'Reserved Parking', 'Signage Rights'],
    agentId: 'usman',
  },
  {
    id: 'townhouse-birchwood',
    title: 'Birchwood Corner Townhouse',
    type: 'townhouse',
    purpose: 'rent',
    price: 1650,
    location: 'Askari 11, Lahore',
    bedrooms: 3,
    bathrooms: 3,
    area: 2100,
    image: '../images/prop-townhouse-2.png',
    homeImage: 'images/prop-townhouse-2.png',
    tag: 'For Rent',
    description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet. A corner-unit townhouse with extra natural light and a small private front yard.',
    amenities: ['Private Yard', 'Gated Community', 'Backup Generator', 'Store Room'],
    agentId: 'hamza',
  },
  {
    id: 'villa-almeria',
    title: 'Almeria Garden Villa',
    type: 'villa',
    purpose: 'sale',
    price: 320000,
    location: 'Bahria Town, Islamabad',
    bedrooms: 6,
    bathrooms: 6,
    area: 5000,
    image: '../images/prop-villa-3.png',
    homeImage: 'images/prop-villa-3.png',
    tag: 'Exclusive',
    description: 'Temporibus autem quibusdam et aut officiis debitis aut rerum. A grand family villa on a corner plot, with mature gardens and a dedicated guest wing.',
    amenities: ['Guest Wing', 'Mature Garden', 'Home Theatre', '4-Car Garage', 'Solar Power', 'Servant Quarters'],
    agentId: 'sadia',
  },
  {
    id: 'apt-riverside',
    title: 'Riverside Court 8D',
    type: 'apartment',
    purpose: 'rent',
    price: 1350,
    location: 'Johar Town, Lahore',
    bedrooms: 2,
    bathrooms: 2,
    area: 1180,
    image: '../images/prop-apartment-3.png',
    homeImage: 'images/prop-apartment-3.png',
    tag: 'For Rent',
    description: 'Et harum quidem rerum facilis est et expedita distinctio. A comfortable two-bedroom rental close to the canal, with quick access to major roads.',
    amenities: ['Balcony', 'Covered Parking', 'Backup Power', 'Elevator'],
    agentId: 'usman',
  },
];

if (typeof module !== 'undefined') module.exports = PROPERTIES;
